services:
  - type: web
    name: flask-backend
    env: python
    buildCommand: pip install -r requirements.txt && pip install --upgrade pip
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7